// Application Data and Configuration

const TRANSLATIONS = {
    "en-US": {
        "flashcardsCode": "Learn Chinese with Flashcards",
        "slideToUnlock": "slide to unlock",
        "pasteCodePlaceholder": "paste or type your unique code here...",
        "generatingTitle": "Loading your flashcard set...",
        "generatingSubtitle": "Please wait while we prepare your cards...",
        "createNewFlashcardsLink": "Enter new code",
        "collection": "Collection",
        "backToStudy": "Back to Study",
        "noCollectedCards": "No cards collected yet"
    }
};
// deck for chinese-pinyin
const CHINESE_VOCABULARY = [
    { front: "爸爸\nbà ba", back: "dad\nพ่อ", emoji: "👨‍👧‍👦" },
    { front: "别\nbié", back: "don't\nอย่า", emoji: "🚫" },
    { front: "朋友\npéng yǒu", back: "friend\nเพื่อน", emoji: "👫" },
    { front: "怕\npà", back: "to fear\nกลัว", emoji: "😨" },
    { front: "妈妈\nmā ma", back: "mom\nแม่", emoji: "👩‍👧‍👦" },
    { front: "买\nmǎi", back: "to buy\nซื้อ", emoji: "🛒" },
    { front: "饭\nfàn", back: "meal\nข้าว", emoji: "🍽️" },
    { front: "富\nfù", back: "rich\nรวย", emoji: "💰" },
    { front: "奶奶\nnǎi nai", back: "grandmother\nยาย", emoji: "👵" },
    { front: "你\nnǐ", back: "you\nคุณ", emoji: "👤" },
    { front: "老\nlǎo", back: "old\nแก่", emoji: "🧓" },
    { front: "来\nlái", back: "to come\nมา", emoji: "➡️" },
    { front: "大\ndà", back: "big\nใหญ่", emoji: "📏" },
    { front: "得\ndé", back: "to get\nได้รับ", emoji: "🏆" },
    { front: "跳\ntiào", back: "to jump\nกระโดด", emoji: "🤸" },
    { front: "调\ntiáo", back: "to adjust\nปรับ", emoji: "⚙️" },
    { front: "猪\nzhū", back: "pig\nหมู", emoji: "🐷" },
    { front: "住\nzhù", back: "to live\nอาศัย", emoji: "🏠" },
    { front: "吃\nchī", back: "to eat\nกิน", emoji: "🍽️" },
    { front: "出\nchū", back: "to go out\nออกไป", emoji: "🚪" },
    { front: "高\ngāo", back: "high\nสูง", emoji: "📏" },
    { front: "个\ngè", back: "measure word\nลักษณนาม", emoji: "📊" },
    { front: "裤\nkù", back: "trousers\nกางเกง", emoji: "👖" },
    { front: "可以\nkě yǐ", back: "can\nสามารถ", emoji: "✅" },
    { front: "虎\nhǔ", back: "tiger\nเสือ", emoji: "🐅" },
    { front: "好\nhǎo", back: "good\nดี", emoji: "👍" },
    { front: "家\njiā", back: "home\nบ้าน", emoji: "🏡" },
    { front: "就\njiù", back: "then\nแล้ว", emoji: "⏭️" },
    { front: "小\nxiǎo", back: "small\nเล็ก", emoji: "🐭" },
    { front: "喜欢\nxǐ huān", back: "to like\nชอบ", emoji: "❤️" },
    { front: "起\nqǐ", back: "to rise\nลุกขึ้น", emoji: "⬆️" },
    { front: "气\nqì", back: "air\nอากาศ", emoji: "💨" },
    { front: "瘦\nshòu", back: "thin\nผอม", emoji: "🩲" },
    { front: "上\nshàng", back: "up\nขึ้น", emoji: "⬆️" },
    { front: "热\nrè", back: "hot\nร้อน", emoji: "🌡️" },
    { front: "让\nràng", back: "to let\nให้", emoji: "🤲" },
    { front: "菜\ncài", back: "dish\nจาน", emoji: "🥗" },
    { front: "才\ncái", back: "just now\nเพิ่ง", emoji: "⏰" },
    { front: "要\nyào", back: "to want\nอยาก", emoji: "💭" },
    { front: "有\nyǒu", back: "to have\nมี", emoji: "📦" },
    { front: "在\nzài", back: "at\nอยู่", emoji: "📍" },
    { front: "走\nzǒu", back: "to walk\nเดิน", emoji: "🚶" },
    { front: "三\nsān", back: "three\nสาม", emoji: "3️⃣" },
    { front: "四\nsì", back: "four\nสี่", emoji: "4️⃣" },
    { front: "问\nwèn", back: "to ask\nถาม", emoji: "❓" },
    { front: "舞\nwǔ", back: "dance\nเต้นรำ", emoji: "💃" },
    { front: "女\nnǚ", back: "woman\nผู้หญิง", emoji: "♀️" },
    { front: "去\nqù", back: "to go\nไป", emoji: "➡️" },
    { front: "矮\nǎi", back: "short\nเตี้ย", emoji: "📏" },
    { front: "爱\nài", back: "to love\nรัก", emoji: "❤️" },
    { front: "没\nméi", back: "not\nไม่มี", emoji: "❌" },
    { front: "为什么\nwèi shén me", back: "why\nทำไม", emoji: "❓" },
    { front: "打\ndǎ", back: "to hit\nตี", emoji: "👊" },
    { front: "他\ntā", back: "he/she/it\nเขา", emoji: "👤" },
    { front: "我\nwǒ", back: "I\nฉัน", emoji: "👆" },
    { front: "摸\nmō", back: "to touch\nแตะ", emoji: "👋" },
    { front: "喝\nhē", back: "to drink\nดื่ม", emoji: "🥤" },
    { front: "了\nle", back: "particle\nคำลงท้าย", emoji: "✓" },
    { front: "鸡\njī", back: "chicken\nไก่", emoji: "🐔" },
    { front: "是\nshì", back: "to be/yes\nเป็น/ใช่", emoji: "✓" },
    { front: "不\nbù", back: "no\nไม่", emoji: "❌" },
    { front: "书\nshū", back: "book\nหนังสือ", emoji: "📖" },
    { front: "睡\nshuì", back: "to sleep\nนอนหลับ", emoji: "😴" },
    { front: "水\nshuǐ", back: "water\nน้ำ", emoji: "💧" },
    { front: "到\ndào", back: "to arrive\nถึง", emoji: "📍" },
    { front: "药\nyào", back: "medicine\nยา", emoji: "💊" },
    { front: "肉\nròu", back: "meat\nเนื้อ", emoji: "🥩" },
    { front: "游\nyóu", back: "to swim\nว่ายน้ำ", emoji: "🏊" },
    { front: "球\nqiú", back: "ball\nลูกบอล", emoji: "⚽" },
    { front: "牛\nniú", back: "cow\nวัว", emoji: "🐄" },
    { front: "鞋\nxié", back: "shoe\nรองเท้า", emoji: "👟" },
    { front: "谢\nxiè", back: "to thank\nขอบคุณ", emoji: "🙏" },
    { front: "学\nxué", back: "to learn\nเรียน", emoji: "📚" },
    { front: "觉\njiào", back: "sleep\nนอน", emoji: "😴" },
    { front: "看\nkàn", back: "to look\nดู", emoji: "👁️" },
    { front: "玩\nwán", back: "to play\nเล่น", emoji: "🎮" },
    { front: "很\nhěn", back: "very\nมาก", emoji: "⭐" },
    { front: "人\nrén", back: "people\nคน", emoji: "👥" },
    { front: "心\nxīn", back: "heart\nหัวใจ", emoji: "💖" },
    { front: "新\nxīn", back: "new\nใหม่", emoji: "✨" },
    { front: "困\nkùn", back: "sleepy\nง่วง", emoji: "😪" },
    { front: "春\nchūn", back: "spring\nฤดูใบไม้ผลิ", emoji: "🌸" },
    { front: "云\nyún", back: "cloud\nเมฆ", emoji: "☁️" },
    { front: "军\njūn", back: "army\nกองทัพ", emoji: "🪖" },
    { front: "胖\npàng", back: "fat\nอ้วน", emoji: "🫃" },
    { front: "唱\nchàng", back: "to sing\nร้องเพลง", emoji: "🎤" },
    { front: "生\nshēng", back: "to live\nอยู่", emoji: "🌱" },
    { front: "冷\nlěng", back: "cold\nหนาว", emoji: "🥶" },
    { front: "病\nbìng", back: "illness\nป่วย", emoji: "🤒" },
    { front: "明\nmíng", back: "bright\nสว่าง", emoji: "☀️" },
    { front: "空\nkōng", back: "empty\nว่าง", emoji: "📦" },
    { front: "泳\nyǒng", back: "to swim\nว่ายน้ำ", emoji: "🏊" },
    { front: "笑\nxiào", back: "to laugh\nหัวเราะ", emoji: "😄" },
    { front: "叫\njiào", back: "to call/scream\nเรียก/ตะโกน", emoji: "📢" },
    { front: "夸\nkuā", back: "to praise\nชม", emoji: "👏" },
    { front: "花\nhuā", back: "flower\nดอกไม้", emoji: "🌸" },
    { front: "活\nhuó", back: "to live\nอยู่", emoji: "❤️" },
    { front: "多\nduō", back: "many\nมาก", emoji: "👥" },
    { front: "坏\nhuài", back: "bad\nเสีย", emoji: "😈" },
    { front: "快\nkuài", back: "fast\nเร็ว", emoji: "⚡" },
    { front: "穿\nchuān", back: "to wear\nใส่", emoji: "👕" },
    { front: "全\nquán", back: "entire\nทั้งหมด", emoji: "💯" },
    { front: "床\nchuáng", back: "bed\nเตียง", emoji: "🛏️" },
    { front: "光\nguāng", back: "light\nแสง", emoji: "💡" },
    { front: "想\nxiǎng", back: "to want\nคิด", emoji: "💭" },
    { front: "亮\nliàng", back: "bright\nสว่าง", emoji: "💡" },
    { front: "现\nxiàn", back: "to appear\nปรากฏ", emoji: "👁️" },
    { front: "天\ntiān", back: "day\nวัน", emoji: "📅" },
    { front: "熊\nxióng", back: "bear\nหมี", emoji: "🐻" },
    { front: "穷\nqióng", back: "poor\nจน", emoji: "💸" },
    { front: "元\nyuán", back: "unit of currency\nหน่วยเงิน", emoji: "💰" },
    { front: "远\nyuǎn", back: "far\nไกล", emoji: "🏃" },
    { front: "儿\nér", back: "son\nลูกชาย", emoji: "👦" },
    { front: "二\nèr", back: "two\nสอง", emoji: "2️⃣" }
];

const PINYIN_CARDS = [
    { front: "ang", back: "ang\nFinal compound: 'ahng' sound\nเสียงสระผสม: 'อาง'", emoji: "🗣️" },
    { front: "ing", back: "ing\nFinal compound: 'eeng' sound\nเสียงสระผสม: 'อิง'", emoji: "🗣️" },
    { front: "en", back: "en\nFinal compound: 'uhn' sound\nเสียงสระผสม: 'เอิน'", emoji: "🗣️" },
    { front: "ai", back: "ai\nFinal compound: 'eye' sound\nเสียงสระผสม: 'ไอ'", emoji: "🗣️" },
    { front: "ao", back: "ao\nFinal compound: 'aow' sound\nเสียงสระผสม: 'เอา'", emoji: "🗣️" }
];

// New deck: the-best-child
const THE_BEST_CHILD_CARDS = [
    { front: "难过\nnán guò", back: "sad\nเศร้า", emoji: "😢" },
    { front: "开心\nkāi xīn", back: "happy\nมีความสุข", emoji: "😊" },
    { front: "生气\nshēng qì", back: "angry\nโกรธ", emoji: "😠" },
    { front: "震惊\nzhèn jīng", back: "shocked\nตกใจ", emoji: "😱" },
    { front: "内疚\nnèi jiù", back: "guilty\nรู้สึกผิด", emoji: "😔" },
    { front: "爸爸\nbà ba", back: "dad\nพ่อ", emoji: "👨" },
    { front: "儿子\nér zi", back: "son\nลูกชาย", emoji: "👦" },
    { front: "同学\ntóng xué", back: "classmate\nเพื่อนร่วมชั้น", emoji: "👥" },
    { front: "拥抱\nyōng bào", back: "to hug\nกอด", emoji: "🤗" },
    { front: "分享\nfēn xiǎng", back: "to share\nแบ่งปัน", emoji: "🤝" },
    { front: "画画\nhuà huà", back: "to draw\nวาดรูป", emoji: "🎨" },
    { front: "跳舞\ntiào wǔ", back: "to dance\nเต้นรำ", emoji: "💃" },
    { front: "数学\nshù xué", back: "math\nคณิตศาสตร์", emoji: "🔢" },
    { front: "教室\njiào shì", back: "classroom\nห้องเรียน", emoji: "🏫" },
    { front: "卧室\nwò shì", back: "bedroom\nห้องนอน", emoji: "🛏️" },
    { front: "玩具\nwán jù", back: "toy\nของเล่น", emoji: "🧸" },
    { front: "鼓\ngǔ", back: "drum\nกลอง", emoji: "🥁" },
    { front: "最好的\nzuì hǎo de", back: "the best\nที่ดีที่สุด", emoji: "⭐" },
    { front: "特别\ntè bié", back: "special\nพิเศษ", emoji: "✨" },
    { front: "最可爱的\nzuì kě ài de", back: "the cutest\nน่ารักที่สุด", emoji: "🥰" },
    { front: "够了\ngòu le", back: "enough\nพอแล้ว", emoji: "🛑" },
    { front: "如果\nrú guǒ", back: "if\nถ้า", emoji: "❓" },
    { front: "未来\nwèi lái", back: "future\nอนาคต", emoji: "🔮" },
    { front: "艺术家\nyì shù jiā", back: "artist\nศิลปิน", emoji: "👨‍🎨" },
    { front: "舞蹈家\nwǔ dǎo jiā", back: "dancer\nนักเต้น", emoji: "💃" },
    { front: "科学家\nkē xué jiā", back: "scientist\nนักวิทยาศาสตร์", emoji: "👨‍🔬" },
    { front: "老师\nlǎo shī", back: "teacher\nครู", emoji: "👨‍🏫" }
];

// Helper function for translations
const t = (key) => TRANSLATIONS['en-US']?.[key] || key;

const DAILY_ACTIVITIES_CARDS = [
    { front: "跳舞\ntiàowǔ", back: "dance\nเต้น", emoji: "" },
    { front: "唱歌\nchànggē", back: "sing\nร้องเพลง", emoji: "" },
    { front: "玩\nwán", back: "play\nเล่น", emoji: "" },
    { front: "做饭\nzuòfàn", back: "cook\nทำอาหาร", emoji: "" },
    { front: "种\nzhòng", back: "plant\nปลูก", emoji: "" },
    { front: "烘烤\nhōngkǎo", back: "bake\nอบ", emoji: "" },
    { front: "编织\nbiānzhī", back: "knit\nถัก", emoji: "" },
    { front: "缝纫\nféngrèn", back: "sew\nเย็บ", emoji: "" },
    { front: "雕刻\ndiāokè", back: "sculpt\nปั้น", emoji: "" },
    { front: "穿\nchuān", back: "put on\nใส่", emoji: "" },
    { front: "叫\njiào", back: "call\nเรียก", emoji: "" },
    { front: "折叠\nzhédié", back: "fold\nพับ", emoji: "" },
    { front: "装饰\nzhuāngshì", back: "decorate\nตกแต่ง", emoji: "" },
    { front: "藏\ncáng", back: "hide\nซ่อน", emoji: "" },
    { front: "找\nzhǎo", back: "seek\nหา", emoji: "" },
    { front: "推\ntuī", back: "push\nผลัก", emoji: "" },
    { front: "拉\nlā", back: "pull\nดึง", emoji: "" },
    { front: "梳\nshū", back: "comb\nหวี", emoji: "" },
    { front: "淋浴\nlínyù", back: "shower\nอาบน้ำ", emoji: "" },
    { front: "洗澡\nxǐzǎo", back: "bath\nอาบน้ำ", emoji: "" },
    { front: "擦\ncā", back: "wipe\nเช็ด", emoji: "" },
    { front: "扔\nrēng", back: "throw\nโยน", emoji: "" },
    { front: "选择\nxuǎnzé", back: "choose\nเลือก", emoji: "" },
    { front: "旋转\nxuánzhuǎn", back: "spin\nหมุน", emoji: "" },
    { front: "整理\nzhěnglǐ", back: "tidy up\nจัดเก็บ", emoji: "" },
    { front: "进去\njìnqù", back: "get in\nเข้า", emoji: "" },
    { front: "读\ndú", back: "read\nอ่าน", emoji: "" },
    { front: "写\nxiě", back: "write\nเขียน", emoji: "" },
    { front: "画\nhuà", back: "draw\nวาด", emoji: "" },
    { front: "画画\nhuàhuà", back: "paint\nระบายสี", emoji: "" },
    { front: "清洁\nqīngjié", back: "clean\nทำความสะอาด", emoji: "" },
    { front: "想\nxiǎng", back: "think\nคิด", emoji: "" },
    { front: "买\nmǎi", back: "buy\nซื้อ", emoji: "" },
    { front: "卖\nmài", back: "sell\nขาย", emoji: "" },
    { front: "切\nqiē", back: "cut\nตัด", emoji: "" },
    { front: "修理\nxiūlǐ", back: "fix\nซ่อม", emoji: "" },
    { front: "打破\ndǎpò", back: "break\nทำแตก", emoji: "" },
    { front: "建造\njiànzào", back: "build\nสร้าง", emoji: "" },
    { front: "教\njiāo", back: "teach\nสอน", emoji: "" },
    { front: "看\nkàn", back: "watch\nดู", emoji: "" },
    { front: "听\ntīng", back: "listen\nฟัง", emoji: "" },
    { front: "说话\nshuōhuà", back: "talk\nคุย", emoji: "" },
    { front: "喊\nhǎn", back: "shout\nตะโกน", emoji: "" },
    { front: "耳语\něryǔ", back: "whisper\nกระซิบ", emoji: "" },
    { front: "喝\nhē", back: "drink\nดื่ม", emoji: "" },
    { front: "吃\nchī", back: "eat\nกิน", emoji: "" },
    { front: "哭\nkū", back: "cry\nร้องไห้", emoji: "" },
    { front: "笑\nxiào", back: "laugh\nหัวเราะ", emoji: "" },
    { front: "挖\nwā", back: "dig\nขุด", emoji: "" },
    { front: "跳\ntiào", back: "jump\nกระโดด", emoji: "" },
    { front: "跌倒\ndiēdǎo", back: "fall\nล้ม", emoji: "" },
    { front: "飞\nfēi", back: "fly\nบิน", emoji: "" },
    { front: "钓鱼\ndiàoyú", back: "fish\nตกปลา", emoji: "" },
    { front: "冥想\nmíngxiǎng", back: "meditate\nทำสมาธิ", emoji: "" },
    { front: "漂浮\npiāofú", back: "float\nลอย", emoji: "" },
    { front: "航行\nhángxíng", back: "sail\nแล่นเรือ", emoji: "" },
    { front: "跑\npǎo", back: "run\nวิ่ง", emoji: "" },
    { front: "竞争\njìngzhēng", back: "compete\nแข่งขัน", emoji: "" },
    { front: "起床\nqǐchuáng", back: "wake up\nตื่นนอน", emoji: "" },
    { front: "走\nzǒu", back: "walk\nเดิน", emoji: "" },
    { front: "睡觉\nshuìjiào", back: "sleep\nนอน", emoji: "" },
    { front: "骑\nqí", back: "ride\nขี่", emoji: "" },
    { front: "潜水\nqiánshuǐ", back: "dive\nดำน้ำ", emoji: "" },
    { front: "划船\nhuáchuán", back: "row\nพายเรือ", emoji: "" },
    { front: "学习\nxuéxí", back: "study\nเรียน", emoji: "" },
    { front: "露营\nlùyíng", back: "camp\nตั้งแคมป์", emoji: "" },
    { front: "瑜伽\nyújiā", back: "yoga\nโยคะ", emoji: "" },
    { front: "锻炼\nduànliàn", back: "exercise\nออกกำลังกาย", emoji: "" },
    { front: "滑雪\nhuáxuě", back: "ski\nเล่นสกี", emoji: "" },
    { front: "滑冰\nhuábīng", back: "skate\nเล่นสเก็ต", emoji: "" },
    { front: "冲浪\nchōnglàng", back: "surf\nเล่นเซิร์ฟ", emoji: "" },
    { front: "游泳\nyóuyǒng", back: "swim\nว่ายน้ำ", emoji: "" },
    { front: "爬\npá", back: "climb\nปีน", emoji: "" },
    { front: "徒步\ntúbù", back: "hike\nเดินป่า", emoji: "" }
];

const OPPOSITES_CARDS = [
    { front: "宽\nkuān", back: "wide\nกว้าง", emoji: "" },
    { front: "窄\nzhǎi", back: "narrow\nแคบ", emoji: "" },
    { front: "下沉\nxiàchén", back: "sink (verb)\nจม", emoji: "" },
    { front: "漂浮\npiāofú", back: "float (verb)\nลอย", emoji: "" },
    { front: "对\nduì", back: "right (correct)\nถูก", emoji: "" },
    { front: "错\ncuò", back: "wrong (incorrect)\nผิด", emoji: "" },
    { front: "轻\nqīng", back: "light (weight)\nเบา", emoji: "" },
    { front: "重\nzhòng", back: "heavy\nหนัก", emoji: "" },
    { front: "黑\nhēi", back: "black\nดำ", emoji: "" },
    { front: "白\nbái", back: "white\nขาว", emoji: "" },
    { front: "强壮\nqiángzhuàng", back: "strong\nแข็งแรง", emoji: "" },
    { front: "弱\nruò", back: "weak\nอ่อนแอ", emoji: "" },
    { front: "年轻\nniánqīng", back: "young\nอายุน้อย", emoji: "" },
    { front: "老\nlǎo", back: "old (person)\nแก่", emoji: "" },
    { front: "旧\njiù", back: "old (thing)\nเก่า", emoji: "" },
    { front: "新\nxīn", back: "new\nใหม่", emoji: "" },
    { front: "右\nyòu", back: "right (direction)\nขวา", emoji: "" },
    { front: "左\nzuǒ", back: "left (direction)\nซ้าย", emoji: "" },
    { front: "湿\nshī", back: "wet\nเปียก", emoji: "" },
    { front: "干\ngān", back: "dry\nแห้ง", emoji: "" },
    { front: "下\nxià", back: "down\nลง", emoji: "" },
    { front: "上\nshàng", back: "up\nขึ้น", emoji: "" },
    { front: "瘦\nshòu", back: "thin (person)\nผอม", emoji: "" },
    { front: "胖\npàng", back: "fat\nอ้วน", emoji: "" },
    { front: "热\nrè", back: "hot\nร้อน", emoji: "" },
    { front: "冷\nlěng", back: "cold\nหนาว", emoji: "" },
    { front: "快乐\nkuàilè", back: "happy\nมีความสุข", emoji: "" },
    { front: "伤心\nshāngxīn", back: "sad\nเศร้า", emoji: "" },
    { front: "快\nkuài", back: "fast\nเร็ว", emoji: "" },
    { front: "慢\nmàn", back: "slow\nช้า", emoji: "" },
    { front: "硬\nyìng", back: "hard\nแข็ง", emoji: "" },
    { front: "软\nruǎn", back: "soft\nนิ่ม", emoji: "" },
    { front: "拉\nlā", back: "pull (verb)\nดึง", emoji: "" },
    { front: "推\ntuī", back: "push (verb)\nผลัก", emoji: "" },
    { front: "小\nxiǎo", back: "small\nเล็ก", emoji: "" },
    { front: "大\ndà", back: "big\nใหญ่", emoji: "" },
    { front: "上面\nshàngmiàn", back: "over\nเหนือ", emoji: "" },
    { front: "下面\nxiàmiàn", back: "under\nใต้", emoji: "" },
    { front: "晚上\nwǎnshang", back: "night\nกลางคืน", emoji: "" },
    { front: "白天\nbáitiān", back: "day\nกลางวัน", emoji: "" },
    { front: "高\ngāo", back: "tall\nสูง", emoji: "" },
    { front: "矮\nǎi", back: "short (height)\nเตี้ย", emoji: "" },
    { front: "满\nmǎn", back: "full\nเต็ม", emoji: "" },
    { front: "空\nkōng", back: "empty\nว่างเปล่า", emoji: "" },
    { front: "厚\nhòu", back: "thick\nหนา", emoji: "" },
    { front: "薄\nbáo", back: "thin (object)\nบาง", emoji: "" },
    { front: "关\nguān", back: "close (verb)\nปิด", emoji: "" },
    { front: "开\nkāi", back: "open (verb)\nเปิด", emoji: "" },
    { front: "短\nduǎn", back: "short (length)\nสั้น", emoji: "" },
    { front: "长\ncháng", back: "long\nยาว", emoji: "" },
    { front: "脏\nzāng", back: "dirty\nสกปรก", emoji: "" },
    { front: "干净\ngānjìng", back: "clean\nสะอาด", emoji: "" },
    { front: "松\nsōng", back: "loose\nหลวม", emoji: "" },
    { front: "紧\njǐn", back: "tight\nแน่น", emoji: "" },
    { front: "外面\nwàimiàn", back: "out\nข้างนอก", emoji: "" },
    { front: "里面\nlǐmiàn", back: "in\nข้างใน", emoji: "" },
    { front: "哭\nkū", back: "cry (verb)\nร้องไห้", emoji: "" },
    { front: "笑\nxiào", back: "laugh (verb)\nหัวเราะ", emoji: "" },
    { front: "前面\nqiánmiàn", back: "front\nข้างหน้า", emoji: "" },
    { front: "后面\nhòumiàn", back: "back\nข้างหลัง", emoji: "" },
    { front: "远\nyuǎn", back: "far\nไกล", emoji: "" },
    { front: "近\njìn", back: "near\nใกล้", emoji: "" },
    { front: "坏\nhuài", back: "bad\nไม่ดี / แย่", emoji: "" },
    { front: "好\nhǎo", back: "good\nดี", emoji: "" }
];

const CAREERS_CARDS = [
    { front: "宇航员\nyǔ háng yuán", back: "astronaut\nนักบินอวกาศ (nák bin à-wong-gàt)", emoji: "" },
    { front: "发明家\nfā míng jiā", back: "inventor\nนักประดิษฐ์ (nák bprà-dìt)", emoji: "" },
    { front: "科学家\nkē xué jiā", back: "scientist\nนักวิทยาศาสตร์ (nák wít-thá-yaa-sàt)", emoji: "" },
    { front: "法官\nfǎ guān", back: "judge\nผู้พิพากษา (pûu pí-pâak-sǎa)", emoji: "" },
    { front: "律师\nlǜ shī", back: "lawyer\nทนายความ (thá-naai kwaam)", emoji: "" },
    { front: "侦探\nzhēn tàn", back: "detective\nนักสืบ (nák sùep)", emoji: "" },
    { front: "拳击手\nquán jī shǒu", back: "boxer\nนักมวย (nák muai)", emoji: "" },
    { front: "运动员\nyùn dòng yuán", back: "sportsman\nนักกีฬา (nák gǐi-laa)", emoji: "" },
    { front: "裁判\ncái pàn", back: "referee\nกรรมการ (gam-má-gaan)", emoji: "" },
    { front: "汽修工\nqì xiū gōng", back: "mechanic\nช่างยนต์ (châng yon)", emoji: "" },
    { front: "电工\ndiàn gōng", back: "electrician\nช่างไฟฟ้า (châng fai-fáa)", emoji: "" },
    { front: "水管工\nshuǐ guǎn gōng", back: "plumber\nช่างประปา (châng bprà-bpaa)", emoji: "" },
    { front: "木匠\nmù jiàng", back: "carpenter\nช่างไม้ (châng mái)", emoji: "" },
    { front: "音乐家\nyīn yuè jiā", back: "musician\nนักดนตรี (nák don-dtrii)", emoji: "" },
    { front: "舞者\nwǔ zhě", back: "dancer\nนักเต้น (nák dtên)", emoji: "" },
    { front: "歌手\ngē shǒu", back: "singer\nนักร้อง (nák rɔ́ɔng)", emoji: "" },
    { front: "油漆工\nyóu qī gōng", back: "painter\nช่างทาสี (châng thâa sǐi)", emoji: "" },
    { front: "建筑工人\njiàn zhù gōng rén", back: "construction worker\nช่างก่อสร้าง (châng gɔ̀-sâang)", emoji: "" },
    { front: "保安\nbǎo ān", back: "security guard\nพนักงานรักษาความปลอดภัย (pá-nák-ngaan rák-sǎa kwaam bplɔ̀t-pai)", emoji: "" },
    { front: "女佣\nnǚ yōng", back: "maid\nแม่บ้าน (mâe bâan)", emoji: "" },
    { front: "接待员\njiē dài yuán", back: "receptionist\nพนักงานต้อนรับ (pá-nák-ngaan dtɔ̂n-ráp)", emoji: "" },
    { front: "DJ\nDJ", back: "Disc jockey\nดีเจ (dii-jêe)", emoji: "" },
    { front: "演讲家\nyǎn jiǎng jiā", back: "Orator\nนักพูด (nák pûut)", emoji: "" },
    { front: "主持人\nzhǔ chí rén", back: "announcer\nพิธีกร (pí-thíi-gɔɔn)", emoji: "" },
    { front: "步兵\nbù bīng", back: "soldier\nทหารราบราบ (thá-hǎan râap)", emoji: "" },
    { front: "空军\nkōng jūn", back: "Air force man\nทหารอากาศ (thá-hǎan aa-gàat)", emoji: "" },
    { front: "海军\nhǎi jūn", back: "navy\nทหารเรือ (thá-hǎan reua)", emoji: "" },
    { front: "老师\nlǎo shī", back: "teacher\nครู (kruu)", emoji: "" },
    { front: "图书管理员\ntú shū guǎn lǐ yuán", back: "librarian\nบรรณารักษ์ (ban-naa-rák)", emoji: "" },
    { front: "清洁工\nqīng jié gōng", back: "Janitor\nภารโรง (paa-rá-roong)", emoji: "" },
    { front: "商人\nshāng rén", back: "businessman\nนักธุรกิจ (nák thú-rá-gìt)", emoji: "" },
    { front: "秘书\nmì shū", back: "secretary\nเลขานุการ (lee-kǎa-nú-gaan)", emoji: "" },
    { front: "会计师\nkuài jì shī", back: "accountant\nพนักงานบัญชี (pá-nák-ngaan ban-chii)", emoji: "" },
    { front: "艺术家\nyì shù jiā", back: "artist\nศิลปิน (sǐn-lá-bpin)", emoji: "" },
    { front: "陶艺家\ntáo yì jiā", back: "potter\nช่างปั้นหม้อ (châng bpân mɔ̂ɔ)", emoji: "" },
    { front: "雕刻师\ndiāo kè shī", back: "carver\nช่างแกะสลัก (châng gè-sà-làk)", emoji: "" },
    { front: "演员\nyǎn yuán", back: "actor\nนักแสดงชาย (nák sà-daeng chaai)", emoji: "" },
    { front: "导演\ndǎo yǎn", back: "movie director\nผู้กำกับการแสดง (phûu-gam-gàp-kaan-sà-daeng)", emoji: "" },
    { front: "女演员\nnǚ yǎn yuán", back: "actress\nนักแสดงหญิง (nák sà-daeng yǐng)", emoji: "" },
    { front: "政治家\nzhèng zhì jiā", back: "politician\nนักการเมือง (nák gaan-meuang)", emoji: "" },
    { front: "公司职员\nzhí yuán", back: "office worker\nพนักงานบริษัท（phá-nák-ngaan bɔ̀-rí-sàt）", emoji: "" },
    { front: "业务员\nyè wù yuán", back: "operator\nพนักงานต่อโทรศัพท์ (pá-nák-ngaan dtɔ̀ɔ thoo-rá-sàp)", emoji: "" },
    { front: "出租车司机\nchū zū chē sī jī", back: "taxi driver\nคนขับแท็กซี่ (kon kàp táek-sîi)", emoji: "" },
    { front: "火车司机\nhuǒ chē sī jī", back: "engine driver\nคนขับรถไฟ (kon kàp rót-fai)", emoji: "" },
    { front: "公交车司机\ngōng jiāo chē sī jī", back: "bus driver\nคนขับรถโดยสาร (kon kàp rót doi-sǎan)", emoji: "" },
    { front: "花店老板\nhuā diàn lǎo bǎn", back: "florist\nคนขายดอกไม้ (kon kǎai dɔ̀ɔk-mái)", emoji: "" },
    { front: "屠夫\ntú fū", back: "butcher\nคนขายเนื้อสัตว์ (kon kǎai núea sàt)", emoji: "" },
    { front: "水果小贩\nshuǐ guǒ xiǎo fàn", back: "fruit seller\nคนขายผลไม้ (kon kǎai pǒn-lá-mái)", emoji: "" },
    { front: "理发师\nlǐ fà shī", back: "barber\nช่างตัดผมสำหรับผู้ชาย", emoji: "" },
    { front: "美发师\nměi fà shī", back: "hairdresser\nช่างทำผมสำหรับผู้หญิง", emoji: "" },
    { front: "男装裁缝\nnán zhuāng cái féng", back: "tailor\nช่างตัดเสื้อสำหรับผู้ชาย ", emoji: "" },
    { front: "女装裁缝\nnǚ zhuān cái féng", back: "dress maker\nช่างตัดเสื้อสำหรับผู้หญิง", emoji: "" },
    { front: "鞋匠\nxié jiàng", back: "shoemaker\nช่างทำรองเท้า", emoji: "" },
    { front: "锁匠\nsuǒ jiàng", back: "keysmith\nช่างทำลูกกุญแจ", emoji: "" },
    { front: "钟表匠\nzhōng biǎo jiàng", back: "watchmaker\nช่างทำนาฬิกา", emoji: "" },
    { front: "摄影师\nshè yǐng shī", back: "photographer\nช่างถ่ายภาพ", emoji: "" },
    { front: "报告人\nbào gào rén", back: "presenter\nผู้นำเสนอ", emoji: "" },
    { front: "模特\nmó tè", back: "model\nนางแบบ (naang bàep)", emoji: "" },
    { front: "魔术师\nmó shù shī", back: "magician\nนักมายากล (nák maa-yaa-gon)", emoji: "" },
    { front: "杂技演员\nzá jì yǎn yuán", back: "acrobat\nนักแสดงกายกรรม", emoji: "" },
    { front: "小丑\nxiǎo chǒu", back: "joker\nนักแสดงตลก", emoji: "" },
    { front: "考古学家\nkǎo gǔ xué jiā", back: "archaeologist\nนักโบราณคดี (nák boo-raan-ná-ká-dii)", emoji: "" },
    { front: "潜水员\nqián shuǐ yuán", back: "diver\nนักประดาน้ำ", emoji: "" },
    { front: "医生\nyī shēng", back: "doctor\nแพทย์ (pâet)", emoji: "" },
    { front: "牙医\nyá yī", back: "dentist\nทันตแพทย์", emoji: "" },
    { front: "兽医\nshòu yī", back: "veterinarian\nสัตวแพทย์ (sàt-dtà-wá-pâet)", emoji: "" },
    { front: "护士\nhù shì", back: "nurse\nนางพยาบาล", emoji: "" },
    { front: "药剂师\nyào jì shī", back: "pharmacist\nเภสัชกร (phee-sàt-chá-gɔɔn)", emoji: "" },
    { front: "理疗师\nlǐ liáo shī", back: "physiotherapist\nนักกายภาพบำบัด (nák gaai-yá-pâap bam-bàt)", emoji: "" },
    { front: "厨师\nchú shī", back: "chef\nพ่อครัว (pɔ̂ɔ krua)", emoji: "" },
    { front: "面包师\nmiàn bāo shī", back: "baker\nคนทำขนมปัง (kon tham kà-nǒm bpang)", emoji: "" },
    { front: "服务员 (男)\nfú wù yuán (nán)", back: "waiter\nบริกรชาย (bɔɔ-rí-gɔɔn chaai)", emoji: "" },
    { front: "服务员 (女)\nfú wù yuán (nǚ)", back: "waitress\nบริกรหญิง (bɔɔ-rí-gɔɔn yǐng)", emoji: "" },
    { front: "农民\nnóng mín", back: "farmer\nชาวนา (chaao naa）", emoji: "" },
    { front: "果农\nguǒ nóng", back: "orchardist\nชาวสวน （chaao sǔuan)", emoji: "" },
    { front: "渔民\nyú mín", back: "fisherman\nชาวประมง (chaao bprà-mong)", emoji: "" },
    { front: "警察\njǐng chá", back: "policeman\nตำรวจ (dtam-rùuat)", emoji: "" },
    { front: "交警\njiāo jǐng", back: "traffic corp\nตำรวจจราจร (dtam-rùuat jà-raa-jɔɔn)", emoji: "" },
    { front: "消防员\nxiāo fáng yuán", back: "fireman\nพนักงานดับเพลิง", emoji: "" },
    { front: "邮递员\nyóu dì yuán", back: "postman\nบุรุษไปรษณีย์ (bù-rùt bprai-sà-nii)", emoji: "" },
    { front: "送货员\nsòng huò yuán", back: "delivery person\nคนส่งของ (kon sòng kɔ̌ɔng)", emoji: "" },
    { front: "飞行员\nfēi xíng yuán", back: "pilot\nนักบิน (nák bin)", emoji: "" },
    { front: "空少\nkōng shǎo", back: "steward\nพนักงานต้อนรับชาย (pá-nák-ngaan dtɔ̂n-ráp chaai)", emoji: "" },
    { front: "空姐\nkōng jiě", back: "air hostess\nพนักงานต้อนรับหญิง (pá-nák-ngaan dtɔ̂n-ráp yǐng)", emoji: "" },
    { front: "建筑师\njiàn zhù shī", back: "architect\nสถาปนิก (sà-thǎa-bpà-ník)", emoji: "" },
    { front: "工长\ngōng zhǎng", back: "foreman\nหัวหน้าคนงาน (hǔua-nâa kon ngaan)", emoji: "" },
    { front: "工程师\ngōng chéng shī", back: "engineer\nวิศวกร (wít-sà-wá-gɔɔn)", emoji: "" },
    { front: "作家\nzuò jiā", back: "writer\nนักเขียน (nák kǐian)", emoji: "" },
    { front: "作曲家\nzuò qǔ jiā", back: "song writer\nนักแต่งเพลง (nák dtàeng pleeng)", emoji: "" },
    { front: "新闻记者\nxīn wén jì zhě", back: "journalist\nนักข่าวหนังสือพิมพ์", emoji: "" },
    { front: "导游\ndǎo yóu", back: "guide\nมัคคุเทศก์", emoji: "" },
    { front: "口译员\nkǒu yì yuán", back: "interpreter\nล่าม (lâam)", emoji: "" },
    { front: "报道员\nbào dào yuán", back: "reporter\nผู้สื่อข่าว (pûu sùe kàao)", emoji: "" }
];

const VERBS_CARDS = [
    { front: "开\nkāi", back: "open\nเปิด\nbpèrt", emoji: "" },
    { front: "关\nguān", back: "close\nปิด\nbpìt", emoji: "" },
    { front: "盖\ngài", back: "cover\nคลุม\nklum", emoji: "" },
    { front: "跳舞\ntiàowǔ", back: "dance\nเต้น\ndtên", emoji: "" },
    { front: "唱歌\nchànggē", back: "sing\nร้องเพลง\nráwng pleng", emoji: "" },
    { front: "看\nkàn", back: "watch\nดู\ndoo", emoji: "" },
    { front: "化妆\nhuàzhuāng", back: "put on makeup\nแต่งหน้า\ndtàeng nâa", emoji: "" },
    { front: "穿\nchuān", back: "wear\nใส่\nsài", emoji: "" },
    { front: "扣\nkòu", back: "button\nติดกระดุม\ndtìt grà-dum", emoji: "" },
    { front: "起床\nqǐchuáng", back: "wake up\nตื่นนอน\ndtèun non", emoji: "" },
    { front: "打哈欠\ndǎ hāqian", back: "yawn\nหาว\nhăao", emoji: "" },
    { front: "睡觉\nshuìjiào", back: "sleep\nนอน\nnon", emoji: "" },
    { front: "做饭\nzuòfàn", back: "cook\nทำอาหาร\ntam aa-hăan", emoji: "" },
    { front: "剥\nbō", back: "peel\nปอก\nbpàwk", emoji: "" },
    { front: "剁碎\nduòsuì", back: "mince\nสับ\nsàp", emoji: "" },
    { front: "吃\nchī", back: "eat\nกิน\ngin", emoji: "" },
    { front: "喝\nhē", back: "drink\nดื่ม\ndèum", emoji: "" },
    { front: "吸\nxī", back: "suck\nดูด\ndòot", emoji: "" },
    { front: "看\nkàn", back: "look\nมอง\nmong", emoji: "" },
    { front: "藏\ncáng", back: "hide\nซ่อน\nsâwn", emoji: "" },
    { front: "找\nzhǎo", back: "find\nหา\nhăa", emoji: "" },
    { front: "玩\nwán", back: "play\nเล่น\nlên", emoji: "" },
    { front: "荡\ndàng", back: "swing\nแกว่ง\ngwàeng", emoji: "" },
    { front: "滑\nhuá", back: "slide\nลื่น\nlêun", emoji: "" },
    { front: "乞求\nqǐqiú", back: "beg\nขอ\nkŏr", emoji: "" },
    { front: "给\ngěi", back: "give\nให้\nhâi", emoji: "" },
    { front: "收到\nshōudào", back: "receive\nได้รับ\ndâi-ráp", emoji: "" },
    { front: "看见\nkànjiàn", back: "see\nเห็น\nhĕn", emoji: "" },
    { front: "说话\nshuōhuà", back: "talk\nคุย\nkui", emoji: "" },
    { front: "听\ntīng", back: "listen\nฟัง\nfang", emoji: "" },
    { front: "摸\nmō", back: "touch\nแตะ\ndtáe", emoji: "" },
    { front: "舔\ntiǎn", back: "lick\nเลีย\nlia", emoji: "" },
    { front: "闻\nwén", back: "smell\nดม\ndom", emoji: "" },
    { front: "笑\nxiào", back: "laugh\nหัวเราะ\nhŭa-ráw", emoji: "" },
    { front: "微笑\nwēixiào", back: "smile\nยิ้ม\nyím", emoji: "" },
    { front: "哭\nkū", back: "cry\nร้องไห้\nráwng-hâi", emoji: "" },
    { front: "爱\nài", back: "love\nรัก\nrák", emoji: "" },
    { front: "拥抱\nyōngbào", back: "hug\nกอด\ngàwt", emoji: "" },
    { front: "亲吻\nqīnwěn", back: "kiss\nหอม\nhŏm", emoji: "" },
    { front: "拍手\npāishǒu", back: "clap\nตบมือ\ndtòp meu", emoji: "" },
    { front: "挥手\nhuīshǒu", back: "wave\nโบกมือ\nbòhk meu", emoji: "" },
    { front: "拿\nná", back: "hold\nถือ\ntĕu", emoji: "" },
    { front: "想\nxiǎng", back: "think\nคิด\nkít", emoji: "" },
    { front: "问\nwèn", back: "ask\nถาม\ntăam", emoji: "" },
    { front: "回答\nhuídá", back: "answer\nตอบ\ndtàwp", emoji: "" },
    { front: "洗澡\nxǐzǎo", back: "take a bath\nอาบน้ำ\nàap náam", emoji: "" },
    { front: "大便\ndàbiàn", back: "defecate\nอึ\nèu", emoji: "" },
    { front: "尿尿\nniàoniào", back: "pee\nฉี่\nchèe", emoji: "" },
    { front: "驯服\nxùnfú", back: "tame\nทำให้เชื่อง\ntam hâi chêuang", emoji: "" },
    { front: "打\ndǎ", back: "hit\nตี\ndtee", emoji: "" },
    { front: "射\nshè", back: "shoot\nยิง\nying", emoji: "" },
    { front: "去\nqù", back: "go\nไป\nbpai", emoji: "" },
    { front: "停\ntíng", back: "stop\nหยุด\nyùt", emoji: "" },
    { front: "跟\ngēn", back: "follow\nตาม\ndtaam", emoji: "" },
    { front: "踢\ntī", back: "kick\nเตะ\ndtè", emoji: "" },
    { front: "跳\ntiào", back: "jump\nกระโดด\ngrὰ-dòht", emoji: "" },
    { front: "扔\nrēng", back: "throw\nโยน\nyohn", emoji: "" },
    { front: "跑\npǎo", back: "run\nวิ่ง\nwîng", emoji: "" },
    { front: "爬\npá", back: "crawl\nคลาน\nklaan", emoji: "" },
    { front: "走\nzǒu", back: "walk\nเดิน\ndern", emoji: "" },
    { front: "爬\npá", back: "climb\nปีน\nbpeen", emoji: "" },
    { front: "坐\nzuò", back: "sit\nนั่ง\nnâang", emoji: "" },
    { front: "站\nzhàn", back: "stand\nยืน\nyeun", emoji: "" },
    { front: "选\nxuǎn", back: "choose\nเลือก\nlêuak", emoji: "" },
    { front: "卖\nmài", back: "sell\nขาย\nkăai", emoji: "" },
    { front: "买\nmǎi", back: "buy\nซื้อ\nséu", emoji: "" },
    { front: "摘\nzhāi", back: "pick\nเก็บ\ngèp", emoji: "" },
    { front: "种\nzhòng", back: "plant\nปลูก\nbplòok", emoji: "" },
    { front: "挖\nwā", back: "dig\nขุด\nkùt", emoji: "" },
    { front: "摔倒\nshuāidǎo", back: "tumble\nหกล้ม\nhòk-lóm", emoji: "" },
    { front: "受伤\nshòushāng", back: "injure\nบาดเจ็บ\nbàat-jèp", emoji: "" },
    { front: "咳嗽\nkésou", back: "cough\nไอ\nai", emoji: "" },
    { front: "撕\nsī", back: "tear\nฉีก\nchèek", emoji: "" },
    { front: "切\nqiē", back: "cut\nตัด\ndtàt", emoji: "" },
    { front: "贴\ntiē", back: "stick\nแปะ\nbpàe", emoji: "" },
    { front: "画\nhuà", back: "draw\nวาด\nwâat", emoji: "" },
    { front: "雕\ndiāo", back: "sculpt\nปั้น\nbpân", emoji: "" },
    { front: "涂\ntú", back: "paint\nทาสี\ntaa sĕe", emoji: "" },
    { front: "叫\njiào", back: "call\nเรียก\nrîak", emoji: "" },
    { front: "耳语\něryǔ", back: "whisper\nกระซิบ\ngrὰ-síp", emoji: "" },
    { front: "喊\nhǎn", back: "shout\nตะโกน\ndtá-gohn", emoji: "" },
    { front: "教\njiāo", back: "teach\nสอน\nsŏn", emoji: "" },
    { front: "写\nxiě", back: "write\nเขียน\nkĭan", emoji: "" },
    { front: "读\ndú", back: "read\nอ่าน\nàan", emoji: "" },
    { front: "开车\nkāichē", back: "drive\nขับรถ\nkàp rót", emoji: "" },
    { front: "划\nhuá", back: "paddle\nพาย\npaai", emoji: "" },
    { front: "骑\nqí", back: "ride\nขี่\nkèe", emoji: "" },
    { front: "推\ntuī", back: "push\nดัน\ndan", emoji: "" },
    { front: "背\nbēi", back: "carry\nแบก\nbàek", emoji: "" },
    { front: "举\njǔ", back: "lift\nยก\nyók", emoji: "" },
    { front: "拉\nlā", back: "pull\nดึง\ndeung", emoji: "" },
    { front: "快点\nkuài diǎn", back: "hurry up\nรีบ\nrêep", emoji: "" },
    { front: "喘气\nchuǎnqì", back: "pant\nหอบ\nhàwp", emoji: "" },
    { front: "等\nděng", back: "wait\nรอ\nror", emoji: "" },
    { front: "洗\nxǐ", back: "wash\nล้าง\nláang", emoji: "" },
    { front: "拖地\ntuōdì", back: "mop\nถูพื้น\ntŏo péun", emoji: "" },
    { front: "擦干\ncā gān", back: "dry\nเช็ดให้แห้ง\nchét hâi hâeng", emoji: "" }
];
